# All
AllCops:
  TargetRubyVersion: 2.6
  Exclude:
    - 'vendor/bundle/**/*'
    - 'spec/spec_helper.rb'

# Allow japanese comments
Style/AsciiComments:
  Enabled: false

# Prefer double quoted string literals
Style/StringLiterals:
  EnforcedStyle: double_quotes
